[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
rodio = "0.21.1"
symphonia = { version = "0.5.5", features = ["mp3", "ogg", "flac", "isomp4", "wav", "aac", "pcm", "vorbis"] }
